Repository openclarity/vmclarity, pull requests merged in 2023-12, with the labels that each got.

#1006 ci: group containerd updates
  .github/dependabot.yml
Labels: ci

#1025 refactor: prefix uibackend envs
  cmd/vmclarity-ui-backend/main.go
  docs/configuration.md
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.json
  installation/docker/uibackend.env
  installation/gcp/dm/components/vmclarity-install.sh
  installation/kubernetes/helm/vmclarity/templates/uibackend/deployment.yaml
  pkg/uibackend/config.go
  pkg/uibackend/config_test.go
Labels: ui-backend

#1026 ci: add linting for Azure/Bicep package
  .github/workflows/reusable-verification.yml
Labels: ci

#1030 refactor!: prefix apiserver envs
  cmd/vmclarity-apiserver/main.go
  docs/configuration.md
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.json
  installation/docker/apiserver.env
  installation/gcp/dm/components/vmclarity-install.sh
  installation/kubernetes/helm/vmclarity/templates/apiserver/deployment.yaml
  pkg/apiserver/apiserver.go
  pkg/apiserver/config.go
  pkg/apiserver/config_test.go
  pkg/apiserver/rest/server.go
Labels: api

#1049 ci: group k8s dep updates
  .github/dependabot.yml
Labels: dependencies, ci
