Repository openclarity/vmclarity, pull requests merged in 2023-07, with the labels that each got.

#450 fix: resolve aws volume attachment check
  runtime_scan/pkg/provider/aws/volume.go
Labels: bug

#441 feat(cfn): add arm64 support for controlplane
  installation/aws/VmClarity.cfn
Labels: bug, enhancement

#474 docs: Update scope in scan configuration examples
  docs/scanConfig.json
  docs/test_e2e.md
  docs/testplans/abort-scan.md
Labels: documentation

#462 feat(docker): create docker provider
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  cli/cmd/root.go
  go.mod
  go.sum
  pkg/backend/database/gorm/asset.go
  runtime_scan/pkg/orchestrator/config.go
  runtime_scan/pkg/orchestrator/orchestrator.go
  runtime_scan/pkg/provider/docker/client.go
  runtime_scan/pkg/provider/docker/config.go
  runtime_scan/pkg/provider/docker/container.go
  runtime_scan/pkg/provider/docker/image.go
  shared/pkg/families/config.go
  shared/pkg/families/config_test.go
  ui_backend/api/models/models.gen.go
  ui_backend/api/openapi.yaml
  ui_backend/api/server/server.gen.go
  ui_backend/pkg/rest/dashboard_riskiest_assets.go
Labels: enhancement, docker, go
