Repository openclarity/vmclarity, pull requests merged in 2023-11, with the labels that each got.

#883 fix: chkrootkit binary detection
  pkg/shared/families/rootkits/chkrootkit/chkrootkit.go
Labels: bug

#886 fix: lynis testDB path
  pkg/shared/families/misconfiguration/lynis/scanner.go
  pkg/shared/families/misconfiguration/lynis/testdb.go
Labels: bug

#892 fix: use internal service address in Docker
  installation/docker/orchestrator.env
Labels: bug

#884 test(e2e): replace default families scan with full families scan
  e2e/abort_scan_test.go
  e2e/fail_scan_test.go
  e2e/full_scan_test.go
  e2e/helpers.go
Labels: blocked, e2e tests

#899 feat(ci): lint PR title
  .github/workflows/semantic-pr.yml
Labels: ci

#796 refactor(ci): go caching
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  .github/workflows/reusable-end-to-end-testing.yml
  .github/workflows/reusable-verification.yml
Labels: enhancement, ci

#901 fix(ci): run PR linter once
  .github/workflows/semantic-pr.yml
Labels: ci

#898 fix(ui): calculate completed scans count correctly
  ui/src/layout/Dashboard/CounterDisplay/index.js
  ui/src/layout/Dashboard/index.js
Labels: bug, javascript, ui

#908 chore(deps): use ghcr.io/openclarity/freshclam-mirror:v0.2.0
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity.bicep
  installation/azure/vmclarity.json
  installation/azure/vmclarityDeployModule.bicep
  installation/gcp/dm/components/vmclarity-server.py.schema
  installation/gcp/dm/vmclarity.py.schema
Labels: dependencies

#910 ci: fix permission for PR linter workflow
  .github/workflows/semantic-pr.yml
Labels: ci

#911 ci: use PAT token for dev image cleanup
  .github/workflows/image-cleanup.yml
Labels: ci

#916 docs: remove unused bin path params
  docs/configuration.md
Labels: documentation

#918 ci: enable dev image cleanup
  .github/workflows/image-cleanup.yml
Labels: ci

#919 ci: fix go cache key in release workflow
  .github/workflows/release.yaml
Labels: ci

#923 build: fix building bundles
  .github/workflows/release.yaml
  Makefile
Labels: ci

#924 ci: remove installing ICU on runner
  .github/workflows/release.yaml
Labels: ci

#925 build: rm target dep for release note generation
  Makefile
Labels: bug, ci

#926 ci: fix release notes
  Makefile
Labels: bug, ci

#933 build: fix Scanner image version in Docker bundle
  Makefile
Labels: bug, ci

#954 fix(gcp): installation scripts
  installation/gcp/dm/components/vmclarity-install.sh
Labels: bug, gcp installer

#955 ci: add missing orchestrator dev image to cleanup
  .github/workflows/image-cleanup.yml
Labels: ci

#935 fix(helm): PostgreSQL DB config for API Server
  installation/kubernetes/helm/vmclarity/templates/apiserver/deployment.yaml
Labels: bug

#960 fix(gcp): nil pointer exception
  pkg/orchestrator/provider/gcp/provider.go
Labels: bug, gcp provider

#962 feat(helm): add multiple service types to gateway
  installation/kubernetes/helm/vmclarity/README.md
  installation/kubernetes/helm/vmclarity/templates/gateway/deployment.yaml
  installation/kubernetes/helm/vmclarity/templates/gateway/service-headless.yaml
  installation/kubernetes/helm/vmclarity/templates/gateway/service.yaml
  installation/kubernetes/helm/vmclarity/values.yaml
Labels: enhancement

#967 refactor(docker): change gateway port to 8080
  installation/docker/docker-compose.yml
Labels: docker, docker provider

#966 chore(deps): bump deepmap/oapi-codegen
  api/client/client.gen.go
  api/gen.go
  api/go.mod
  api/go.sum
  api/models/models.gen.go
  api/server/server.gen.go
  api/tools.go
  go.mod
  go.sum
  pkg/uibackend/api/client/client.gen.go
  pkg/uibackend/api/gen.go
  pkg/uibackend/api/models/models.gen.go
  pkg/uibackend/api/server/server.gen.go
  pkg/uibackend/api/tools.go
Labels: dependencies, go

#871 test(uibackend): add e2e tests for ui backend
  e2e/full_scan_test.go
  e2e/suite_test.go
  e2e/testenv/docker/docker.go
  e2e/testenv/types/types.go
  pkg/shared/uibackendclient/client.go
Labels: e2e tests, ui-backend

#946 docs: add rfc for e2e type safety
  rfc/end-to-end-type-safe-apis.md
Labels: rfc

#972 refactor(ui): improve findings impact dashboard
  pkg/uibackend/api/models/models.gen.go
  pkg/uibackend/api/openapi.yaml
  pkg/uibackend/api/server/server.gen.go
  pkg/uibackend/rest/dashboard_findings_impact.go
  pkg/uibackend/rest/dashboard_findings_impact_test.go
  ui/src/layout/Dashboard/FindingsImpactWidget/index.js
Labels: ui-backend, ui

#943 fix(uibackend): repeated items in impact dashboard
  pkg/orchestrator/assetscanprocessor/exploits.go
  pkg/orchestrator/assetscanprocessor/vulnerabilities.go
  pkg/shared/findingkey/common.go
  pkg/shared/findingkey/common_test.go
  pkg/shared/findingkey/exploit.go
  pkg/shared/findingkey/malware.go
  pkg/shared/findingkey/misconfiguration.go
  pkg/shared/findingkey/package.go
  pkg/shared/findingkey/rootkit.go
  pkg/shared/findingkey/secret.go
  pkg/shared/findingkey/vulnerability.go
  ui/src/layout/Dashboard/FindingsImpactWidget/index.js
Labels: ui-backend, ui

#995 ci: group dependency updates
  .github/dependabot.yml
Labels: ci
