Repository openclarity/vmclarity, pull requests merged in 2023-06, with the labels that each got.

#368 Ensure we cast to JSON while build JSON objects
  backend/pkg/database/odatasql/jsonsql/postgres.go
  backend/pkg/database/odatasql/jsonsql/sqlite.go
  backend/pkg/database/odatasql/jsonsql/variant.go
  backend/pkg/database/odatasql/query.go
  backend/pkg/database/odatasql/query_test.go
Labels: bug

#377 feat: bump version for GORM and drivers
  .golangci.yml
  go.mod
  go.sum
Labels: dependencies, go

#273 Add ability to configure timeout for Scans
  api/models/models.gen.go
  api/models/scan.go
  api/models/scanconfig.go
  api/models/scanconfigsnapshot.go
  api/openapi.yaml
  api/server/server.gen.go
  backend/pkg/database/gorm/odata.go
  runtime_scan/pkg/orchestrator/scanconfigwatcher/helpers.go
  runtime_scan/pkg/orchestrator/scanwatcher/config.go
  runtime_scan/pkg/orchestrator/scanwatcher/helpers.go
  runtime_scan/pkg/orchestrator/scanwatcher/watcher.go
Labels: enhancement, go

#386 fix: query for ScanResults to be reconciled
  runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go
Labels: bug

#384 refactor: add delayed startup of Controllers
  runtime_scan/pkg/orchestrator/config.go
  runtime_scan/pkg/orchestrator/orchestrator.go
Labels: enhancement

#392 fix: query for fetching ScanResults in Processor
  runtime_scan/pkg/orchestrator/scanresultprocessor/processor.go
Labels: bug

#393 fix(ui): ScanResult status mapping
  ui/src/layout/AssetScans/StatusIndicator/index.js
Labels: bug

#399 fix(aws): incorrectly set AWS provider kind
  runtime_scan/pkg/provider/aws/client.go
  runtime_scan/pkg/provider/aws/helpers.go
  runtime_scan/pkg/provider/aws/types.go
Labels: bug

#403 fix: patching aborted scan
  runtime_scan/pkg/orchestrator/scanwatcher/watcher.go
Labels: bug

#402 refactor: reconcile event
  runtime_scan/pkg/orchestrator/common/event.go
  runtime_scan/pkg/orchestrator/common/poller.go
  runtime_scan/pkg/orchestrator/common/queue.go
  runtime_scan/pkg/orchestrator/common/queue_test.go
  runtime_scan/pkg/orchestrator/common/reconciler.go
  runtime_scan/pkg/orchestrator/scanconfigwatcher/event.go
  runtime_scan/pkg/orchestrator/scanconfigwatcher/watcher.go
  runtime_scan/pkg/orchestrator/scanresultprocessor/processor.go
  runtime_scan/pkg/orchestrator/scanresultwatcher/event.go
  runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go
  runtime_scan/pkg/orchestrator/scanwatcher/event.go
  runtime_scan/pkg/orchestrator/scanwatcher/watcher.go
Labels: enhancement

#388 refactor: provider configuration
  backend/pkg/backend/backend.go
  docs/configuration.md
  installation/aws/VmClarity.cfn
  runtime_scan/pkg/orchestrator/config.go
  runtime_scan/pkg/orchestrator/orchestrator.go
  runtime_scan/pkg/orchestrator/scanresultwatcher/config.go
  runtime_scan/pkg/orchestrator/scanresultwatcher/helpers.go
  runtime_scan/pkg/provider/aws/client.go
  runtime_scan/pkg/provider/aws/config.go
  runtime_scan/pkg/provider/aws/config_test.go
  runtime_scan/pkg/provider/types.go
Labels: enhancement

#415 feat: bump github.com/anchore/sqlite
  .golangci.yml
  go.mod
  go.sum
Labels: dependencies, go

#425 feat: add fsutils
  cli/cmd/root.go
  cli/pkg/cli/cli.go
  cli/pkg/cli/cli_test.go
  cli/pkg/mount/mount.go
  go.mod
  go.sum
  shared/pkg/command/command.go
  shared/pkg/command/result.go
  shared/pkg/fsutils/blockdevice/linux.go
  shared/pkg/fsutils/blockdevice/unsupported.go
  shared/pkg/fsutils/filesystem/types.go
  shared/pkg/fsutils/lsblk/blockdevice.go
  shared/pkg/fsutils/lsblk/bytes.go
  shared/pkg/fsutils/lsblk/bytes_test.go
  shared/pkg/fsutils/lsblk/internal/scan.go
  shared/pkg/fsutils/lsblk/internal/scan_test.go
  shared/pkg/fsutils/lsblk/json.go
  shared/pkg/fsutils/lsblk/json_test.go
  shared/pkg/fsutils/lsblk/lsblk.go
  shared/pkg/fsutils/lsblk/pairs.go
  shared/pkg/fsutils/lsblk/pairs_test.go
  shared/pkg/fsutils/lsblk/testdata/lsblk.alpine.json
  shared/pkg/fsutils/lsblk/testdata/lsblk.pair.txt
  shared/pkg/fsutils/lsblk/testdata/lsblk.ubuntu.json
  shared/pkg/fsutils/mount/unix.go
  shared/pkg/fsutils/mount/unsupported.go
Labels: bug, enhancement

#423 fix: multiarch docker image
  Dockerfile.backend
Labels: bug, docker

#435 fix: Volume mount scanner host fs into scanner container
  runtime_scan/pkg/provider/cloudinit/cloud-init.tmpl.yaml
  runtime_scan/pkg/provider/cloudinit/testdata/cloud-init.yaml
Labels: bug

#427 fix: ScanResults stuck in aborted state
  runtime_scan/pkg/orchestrator/config.go
  runtime_scan/pkg/orchestrator/scanresultwatcher/config.go
  runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go
Labels: bug, enhancement

#411 feat: update ubuntu server in cloudformation to 22.04 LTS
  installation/aws/VmClarity.cfn
Labels: enhancement
