Repository openclarity/vmclarity, pull requests merged in 2023-09, with the labels that each got.

#614 fix(orchestrator): skip mark terminated if asset found but patch failed
  pkg/orchestrator/discovery/discoverer.go
Labels: bug

#660 feat(test): build all services when running e2e tests
  Makefile
Labels: enhancement, test

#663 docs: add workflow status and go report card to readme file
  README.md
Labels: documentation

#683 refactor: improve e2e documentation and small clean up
  .github/workflows/ci.yml
  CONTRIBUTING.md
  api/openapi.yaml
  docs/testplans/abort-scan.md
  e2e/README.md
  e2e/testenv/testenv.go
  installation/docker/README.md
Labels: documentation, enhancement

#697 feat(test): report api output and service logs on failure
  e2e/README.md
  e2e/abort_scan_test.go
  e2e/basic_scan_test.go
  e2e/default_scan_test.go
  e2e/fail_scan_test.go
  e2e/report.go
  e2e/testenv/testenv.go
Labels: enhancement, test

#706 fix: OpenAPI generator version
  api/client/client.gen.go
  api/gen.go
  api/go.mod
  api/go.sum
  api/models/models.cfg.yaml
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  api/tools.go
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: bug, enhancement

#719 feat(api): add annotations
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
Labels: api

#689 feat(scanresult): resource cleanup status refactor
  api/models/assetscan.go
  api/models/models.gen.go
  api/models/resourcecleanupstatus.go
  api/openapi.yaml
  api/server/server.gen.go
  cmd/vmclarity-cli/asset/asset_scan_create.go
  pkg/apiserver/database/gorm/odata.go
  pkg/apiserver/rest/asset_scan_controller.go
  pkg/orchestrator/assetscanwatcher/watcher.go
  pkg/orchestrator/scanwatcher/helpers.go
  pkg/orchestrator/scanwatcher/helpers_test.go
Labels: bug, enhancement, go, api
