Repository openclarity/vmclarity, pull requests merged in 2023-08, with the labels that each got.

#567 fix(link): contributing guide link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#568 docs: add slack invite to README
  README.md
Labels: documentation

#593 feat: add healthz check to orchestrator and to ui backend
  cmd/vmclarity-apiserver/main.go
  cmd/vmclarity-orchestrator/main.go
  cmd/vmclarity-ui-backend/main.go
  installation/docker/dockercompose.yml
  pkg/apiserver/apiserver.go
  pkg/apiserver/config.go
  pkg/orchestrator/config.go
  pkg/orchestrator/orchestrator.go
  pkg/uibackend/config.go
Labels: enhancement

#594 feat(grype-server): bump grype server version to v0.5.0
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-UI.json
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.bicep
  installation/azure/vmclarity.json
  installation/azure/vmclarityDeployModule.bicep
  installation/docker/dockercompose.yml
  installation/docker/grype-server.env
  installation/gcp/dm/components/vmclarity-install.sh
  installation/gcp/dm/components/vmclarity-server.py.schema
  installation/gcp/dm/vmclarity.py.schema
Labels: docker, aws installer, gcp installer, azure installer, infrastructure

#539 feat(test): add end to end tests skeleton and some basic tests
  CONTRIBUTING.md
  Makefile
  e2e/abort_scan_test.go
  e2e/basic_scan_test.go
  e2e/default_scan_test.go
  e2e/docker-compose.override.yml
  e2e/fail_scan_test.go
  e2e/go.mod
  e2e/go.sum
  e2e/helpers.go
  e2e/suite_test.go
  e2e/testenv/testenv.go
  installation/docker/docker-compose.yml
  installation/docker/orchestrator.env
  pkg/apiserver/database/gorm/odata.go
  pkg/orchestrator/provider/docker/client.go
  pkg/shared/backendclient/client.go
  pkg/shared/backendclient/errors.go
Labels: enhancement, test

#606 fix(uibackend): reduce recalculation interval
  e2e/docker-compose.override.yml
  pkg/uibackend/rest/server.go
Labels: enhancement, docker provider

#618 fix(apiserver): change odata filter in check uniqueness for containers
  e2e/basic_scan_test.go
  pkg/apiserver/database/gorm/asset.go
Labels: bug
