Repository openclarity/vmclarity, pull requests merged in 2023-10, with the labels that each got.

#724 feat(api): add allof metadata to assetscan
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  pkg/apiserver/database/gorm/odata.go
Labels: api

#728 feat(ci): add actionlint
  .github/actionlint-matcher.json
  .github/workflows/build-and-push-component.yaml
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  .github/workflows/reusable-build-and-push.yml
  Makefile
Labels: enhancement

#729 feat(ci): improve CI pipeline
  .github/workflows/build-and-push-component.yaml
  .github/workflows/ci.yml
  .github/workflows/main-merge.yml
  .github/workflows/release.yaml
  .github/workflows/reusable-build-and-push.yml
Labels: enhancement

#714 feat(api): add new provider api object
  api/client/client.gen.go
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  e2e/provider_test.go
  pkg/apiserver/database/demo.go
  pkg/apiserver/database/gorm/database.go
  pkg/apiserver/database/gorm/odata.go
  pkg/apiserver/database/gorm/provider.go
  pkg/apiserver/database/types/database.go
  pkg/apiserver/rest/provider_controller.go
  pkg/orchestrator/provider/aws/client.go
  pkg/orchestrator/provider/aws/client_test.go
  pkg/orchestrator/provider/azure/client.go
  pkg/orchestrator/provider/azure/client_test.go
  pkg/shared/backendclient/client.go
  pkg/shared/backendclient/errors.go
Labels: api

#726 feat(api): add provider to asset and to asset scan
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  pkg/apiserver/database/gorm/odata.go
Labels: api

#744 feat(ci): re-enable end-to-end testing
  .github/workflows/ci.yml
  .github/workflows/reusable-build-and-push.yml
  .github/workflows/reusable-end-to-end-testing.yml
  .github/workflows/reusable-image-names.yml
Labels: ci

#745 refactor(ci): verification workflow
  .github/workflows/ci.yml
  .github/workflows/main-merge.yml
  .github/workflows/release.yaml
  .github/workflows/reusable-verification.yml
  Makefile
Labels: enhancement, ci

#746 feat(ci): cleanup cache for PRs
  .github/workflows/cache-cleanup.yml
Labels: enhancement, ci

#743 feat(ci): cleanup published dev container images
  .github/workflows/image-cleanup.yml
Labels: enhancement, ci

#765 feat(api): add annotations to all high level API objects
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  pkg/apiserver/database/gorm/odata.go
Labels: api

#783 fix(ci): cache cleanup script
  .github/scripts/cache-cleanup.sh
  .github/workflows/cache-cleanup.yml
Labels: ci

#772 fix(provider): wrong container image name
  api/models/containerimageinfo.go
  api/models/models.gen.go
  api/openapi.yaml
  api/server/server.gen.go
  e2e/basic_scan_test.go
  pkg/apiserver/database/gorm/asset.go
  pkg/apiserver/database/gorm/odata.go
  pkg/orchestrator/provider/docker/client.go
  pkg/orchestrator/provider/docker/container.go
  pkg/orchestrator/provider/docker/image.go
  pkg/uibackend/rest/dashboard_riskiest_assets.go
  pkg/uibackend/rest/dashboard_riskiest_assets_test.go
  ui/src/utils/utils.js
Labels: api, docker provider

#790 chore(e2e): bump e2e deps
  .golangci.yml
  e2e/go.mod
  e2e/go.sum
Labels: dependencies, go

#828 feat(e2e): bump docker-compose version
  e2e/go.mod
  e2e/go.sum
Labels: dependencies, go

#827 refactor: Dockerfiles
  Dockerfile.apiserver
  Dockerfile.cli
  Dockerfile.orchestrator
  Dockerfile.ui
  Dockerfile.uibackend
  pkg/orchestrator/provider/docker/client.go
Labels: enhancement

#838 feat: add installing tools to Makefile
  Makefile
Labels: enhancement

#839 fix: yara server address in azure deployment
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.json
Labels: bug

#814 refactor: cli tools
  Dockerfile.cli
  pkg/cli/state/testdata/effective-config.json
  pkg/orchestrator/assetscanwatcher/config.go
  pkg/orchestrator/assetscanwatcher/families.go
  pkg/orchestrator/config.go
  pkg/shared/families/malware/clam/clam.go
  pkg/shared/families/malware/yara/config/config.go
  pkg/shared/families/malware/yara/yara.go
  pkg/shared/families/misconfiguration/lynis/reportParser_test.go
  pkg/shared/families/misconfiguration/lynis/scanner.go
  pkg/shared/families/misconfiguration/lynis/testdb.go
  pkg/shared/families/misconfiguration/lynis/testdb_test.go
  pkg/shared/families/misconfiguration/types/config.go
  pkg/shared/families/rootkits/chkrootkit/chkrootkit.go
  pkg/shared/families/secrets/gitleaks/gitleaks.go
Labels: enhancement, breaking change

#842 fix(ci): re-enable license check
  .github/workflows/reusable-verification.yml
  .licensei.toml
Labels: ci

#846 refactor(orchestrator): rename client to provider
  pkg/orchestrator/provider/aws/provider.go
  pkg/orchestrator/provider/aws/provider_test.go
  pkg/orchestrator/provider/azure/blob.go
  pkg/orchestrator/provider/azure/networkInterface.go
  pkg/orchestrator/provider/azure/provider.go
  pkg/orchestrator/provider/azure/provider_test.go
  pkg/orchestrator/provider/azure/scannerVm.go
  pkg/orchestrator/provider/azure/snapshot.go
  pkg/orchestrator/provider/azure/targetDisk.go
  pkg/orchestrator/provider/docker/container.go
  pkg/orchestrator/provider/docker/image.go
  pkg/orchestrator/provider/docker/provider.go
  pkg/orchestrator/provider/external/provider.go
  pkg/orchestrator/provider/gcp/provider.go
  pkg/orchestrator/provider/gcp/provider_test.go
  pkg/orchestrator/provider/gcp/scannerVm.go
  pkg/orchestrator/provider/gcp/snapshot.go
  pkg/orchestrator/provider/gcp/targetDisk.go
Labels: go, aws installer, aws provider, azure provider, gcp provider, docker provider

#843 docs: add RFC template
  rfc/template.md
Labels: documentation

#844 fix: trivy scan timeout config
  pkg/orchestrator/assetscanwatcher/families.go
  pkg/orchestrator/assetscanwatcher/scannerconfig.go
  pkg/orchestrator/config.go
  pkg/orchestrator/config_test.go
Labels: bug

#855 refactor(orchestrator): remove bind mount in docker provider
  e2e/testenv/docker/docker-compose.override.yml
  go.mod
  go.sum
  pkg/orchestrator/provider/docker/provider.go
Labels: go, docker provider

#861 feat(ci): make e2e tests gating
  .github/workflows/ci.yml
Labels: ci
