Repository openclarity/vmclarity, pull requests merged in 2024-05, with the labels that each got.

#1609 feat: store imageid, repodigest and tags from sbom in vulnerability results
  scanner/analyzer/analyzer.go
  scanner/analyzer/merge.go
  scanner/analyzer/syft/syft.go
  scanner/analyzer/trivy/trivy.go
  scanner/analyzer/trivy/trivy_test.go
  scanner/families/vulnerabilities/result.go
  scanner/scanner/grype/common.go
  scanner/scanner/grype/common_test.go
  scanner/scanner/grype/local_grype.go
  scanner/scanner/grype/remote_grype.go
  scanner/scanner/source.go
  scanner/scanner/trivy/scanner.go
  scanner/utils/image_helper/image_helper.go
  scanner/utils/image_helper/image_helper_test.go
  scanner/utils/sbom/sbom.go
Labels: enhancement, go, scanners

#1642 feat: update cloud init and runner to run plugins on cloud envs
  api/openapi.yaml
  api/server/internal/server/server.gen.go
  api/types/types.gen.go
  plugins/runner/internal/containermanager/docker/manager.go
  plugins/runner/runner.go
  provider/cloudinit/cloud-init.tmpl.yaml
  provider/cloudinit/testdata/cloud-init.yaml
Labels: enhancement, component:api

#1652 fix: grype server address in helm template
  installation/kubernetes/helm/vmclarity/templates/orchestrator/deployment.yaml
Labels: provider:kubernetes

#1653 fix(e2e): set directory asset last seen to future time
  e2e/dir_scan_test.go
Labels: bug

#1658 fix: temp solution for ui-backend failing
  api/types/plugin_adapter.go
  installation/docker/docker-compose.yml
Labels: bug, go, component:ui-backend

#1611 feat: add Azure e2e testenv
  Makefile
  e2e/abort_scan_test.go
  e2e/basic_scan_test.go
  e2e/config/config.go
  e2e/config/config_test.go
  e2e/dir_scan_test.go
  e2e/fail_scan_test.go
  e2e/full_scan_test.go
  e2e/go.mod
  e2e/go.sum
  e2e/helpers.go
  e2e/provider_test.go
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.bicep
  installation/azure/vmclarity.json
  installation/azure/vmclarityDeployModule.bicep
  testenv/azure/asset.go
  testenv/azure/azure.go
  testenv/azure/config.go
  testenv/azure/utils.go
  testenv/config.go
  testenv/go.mod
  testenv/go.sum
  testenv/testenv.go
  testenv/utils/ssh.go
Labels: provider:azure, test:e2e

#1660 feat: CIS docker scanner to work with rootfs, dir
  cli/go.mod
  cli/go.sum
  orchestrator/go.mod
  orchestrator/go.sum
  provider/go.mod
  provider/go.sum
  scanner/families/misconfiguration/cisdocker/config.go
  scanner/families/misconfiguration/cisdocker/report.go
  scanner/families/misconfiguration/cisdocker/report_test.go
  scanner/families/misconfiguration/cisdocker/scanner.go
  scanner/go.mod
  scanner/go.sum
Labels: scanners

#1662 feat: helm install notes for kubernetes provider
  installation/kubernetes/helm/vmclarity/templates/NOTES.txt
Labels: provider:kubernetes

#1668 fix: riskiest assets fails with postgres
  api/server/database/gorm/odata.go
  api/server/database/odatasql/jsonsql/postgres.go
  api/server/database/odatasql/jsonsql/sqlite.go
  api/server/database/odatasql/jsonsql/variant.go
  api/server/database/odatasql/query.go
  uibackend/server/dashboard_riskiest_assets.go
Labels: bug, component:api, component:ui-backend

#1680 fix: containerd export strictly matching platform
  containerruntimediscovery/server/containerd/discoverer.go
Labels: bug, kubernetes, provider:kubernetes

#1681 feat(e2e): revisit k8s test env
  Makefile
  e2e/abort_scan_test.go
  e2e/basic_scan_test.go
  e2e/config/config.go
  e2e/config/config_test.go
  e2e/dir_scan_test.go
  e2e/fail_scan_test.go
  e2e/full_scan_test.go
  e2e/helpers.go
  e2e/report.go
  installation/kubernetes/helm/vmclarity/README.md
  installation/kubernetes/helm/vmclarity/values.yaml
  testenv/kubernetes/kind/dockerimageloader.go
Labels: test:e2e, kubernetes, provider:kubernetes

#1682 ci: run k8s tests
  .github/workflows/ci.yml
  .github/workflows/reusable-end-to-end-testing.yml
  Makefile
  testenv/kubernetes/kind/dockerimageloader.go
Labels: ci, test:e2e, kubernetes, provider:kubernetes

#1679 feat: add dependency on healthchecks to docker-compose services
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.json
  installation/docker/docker-compose.postgresql-override.yaml
  installation/docker/docker-compose.yml
  installation/gcp/dm/components/vmclarity-install.sh
Labels: docker, installer:aws, installer:gcp, installer:azure, provider:docker

#1717 chore: update go to 1.22.2
  .go-version
  .golangci.yml
  CONTRIBUTING.md
  api/client/go.mod
  api/server/go.mod
  api/types/go.mod
  cli/go.mod
  cli/presenter/writer.go
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/server/cmd/main.go
  containerruntimediscovery/server/go.mod
  containerruntimediscovery/types/go.mod
  core/go.mod
  e2e/config/config.go
  e2e/go.mod
  e2e/testdata/go.mod
  installation/go.mod
  orchestrator/go.mod
  orchestrator/processor/assetscan/plugins.go
  orchestrator/watcher/scanconfig/schedule.go
  orchestrator/watcher/scanconfig/watcher.go
  plugins/runner/go.mod
  plugins/runner/internal/containermanager/docker/manager.go
  plugins/runner/runner.go
  plugins/sdk-go/example/go.mod
  plugins/sdk-go/example/main.go
  plugins/sdk-go/go.mod
  plugins/sdk-go/plugin/server.go
  plugins/sdk-go/types/types.go
  plugins/store/kics/go.mod
  plugins/store/kics/main.go
  provider/common/utils.go
  provider/docker/provider.go
  provider/go.mod
  provider/kubernetes/container.go
  provider/v2/docker/scanner/scanner.go
  scanner/analyzer/purl.go
  scanner/families/exploits/exploitdb/utils.go
  scanner/families/malware/yara/yara.go
  scanner/families/vulnerabilities/family.go
  scanner/go.mod
  scanner/job_manager/manager.go
  scanner/utils/containerrootfs/todirectory.go
  scanner/utils/vulnerability/vulnerability.go
  testenv/aws/utils.go
  testenv/azure/utils.go
  testenv/gcp/utils.go
  testenv/go.mod
  testenv/kubernetes/kubernetes.go
  testenv/utils/fanout/fanout.go
  testenv/utils/fanout/fanout_test.go
  testenv/utils/fanout/types.go
  testenv/utils/ssh.go
  uibackend/client/go.mod
  uibackend/server/cmd/main.go
  uibackend/server/go.mod
  uibackend/types/go.mod
  utils/go.mod
  workflow/go.mod
Labels: go

#1726 chore: add missing mods to renovate ignore
  renovate.json
Labels: dependencies

#1731 fix: remove race flag from orchestrator docker build
  Makefile
Labels: bug

#1684 fix: use custom network for plugin communication
  plugins/runner/internal/containermanager/docker/client.go
  plugins/runner/internal/containermanager/docker/manager.go
  plugins/runner/internal/containermanager/types.go
  plugins/runner/runner.go
  scanner/families/plugins/runner/runner.go
Labels: scanners

#1743 fix: UI refresh bug
  ui/nginx.conf
  ui/tsconfig.json
  ui/vite.config.ts
Labels: bug, javascript
