Repository openclarity/vmclarity, pull requests merged in 2024-02, with the labels that each got.

#1153 fix(testenv): missing replace in go.mod
  testenv/go.mod
Labels: bug

#1151 refactor: split cr-discovery into multiple modules
  .github/workflows/reusable-build-and-push.yml
  .github/workflows/reusable-image-names.yml
  Dockerfile.cr-discovery-server
  Makefile
  containerruntimediscovery/client/client.go
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/client/go.sum
  containerruntimediscovery/server/cmd/main.go
  containerruntimediscovery/server/go.mod
  containerruntimediscovery/server/go.sum
  containerruntimediscovery/server/pkg/containerd/discoverer.go
  containerruntimediscovery/server/pkg/discoverer.go
  containerruntimediscovery/server/pkg/docker/discoverer.go
  containerruntimediscovery/server/pkg/server.go
  containerruntimediscovery/types/cleanup.go
  containerruntimediscovery/types/discoverer.go
  containerruntimediscovery/types/errors.go
  containerruntimediscovery/types/go.mod
  containerruntimediscovery/types/go.sum
  containerruntimediscovery/types/response.go
  e2e/go.sum
  go.mod
  go.sum
  pkg/orchestrator/provider/kubernetes/container.go
  pkg/orchestrator/provider/kubernetes/image.go
  pkg/orchestrator/provider/kubernetes/provider.go
  testenv/go.sum
Labels: enhancement, go

#1111 feat: add docker bake
  Makefile
  docker-bake.hcl
Labels: docker

#1158 feat: configure goheader lint
  .github/workflows/reusable-verification.yml
  .golangci.yml
  Makefile
  cli/pkg/families/malware/clam/util/clam_util_test.go
Labels: enhancement

#1160 refactor: check licenses in multiple modules
  .github/workflows/reusable-verification.yml
  Makefile
  makefile.d/20-tools.mk
Labels: enhancement, github actions

#1042 docs: change asset-findings relationships rfc
  rfc/change-asset-findings-relationships.md
Labels: enhancement, breaking change, rfc

#1161 ci: fix caching for license check
  .github/workflows/reusable-verification.yml
  .gitignore
Labels: ci

#1162 chore: centralize Go version configuration
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  .github/workflows/reusable-end-to-end-testing.yml
  .github/workflows/reusable-verification.yml
  .go-version
  Makefile
Labels: ci

#1163 ci: verify go modules
  .github/workflows/reusable-verification.yml
  Makefile
  api/server/go.mod
  installation/go.sum
  provider/go.mod
Labels: ci

#1165 chore: improve makefile
  .github/workflows/reusable-end-to-end-testing.yml
  .licensei.toml
  Makefile
Labels: enhancement, ci

#1168 refactor: remove demo and grpclog
  .golangci.yml
  api/server/go.mod
  api/server/go.sum
  api/server/pkg/config.go
  api/server/pkg/config_test.go
  api/server/pkg/database/demo.go
  api/server/pkg/server.go
  docs/configuration.md
  uibackend/server/go.mod
  uibackend/server/go.sum
  utils/go.mod
  utils/go.sum
  utils/log/log.go
Labels: enhancement

#1186 ci: adjust renovate config
  renovate.json
Labels: ci

#1188 fix: path to images
  .dockerignore
  ARCHITECTURE.md
  README.md
  TOUR.md
  installation/aws/README.md
Labels: bug

#1198 ci: fix setting docker digest for latest tag
  renovate.json
Labels: ci

#1221 ci: disable pinning docker images by digest
  renovate.json
Labels: ci

#1202 refactor: rm golang.org/x/exp dependency
  cli/families/exploits/family.go
  cli/go.mod
  cli/go.sum
  core/to/to.go
  testenv/go.mod
  testenv/go.sum
  testenv/utils/fanout/fanout_test.go
Labels: go

#1205 refactor: core/to pkg
  cli/families/rootkits/chkrootkit/utils/parser.go
  cli/presenter/apimodel.go
  core/to/to.go
  core/to/to_test.go
  uibackend/server/dashboard_findings_impact.go
Labels: go

#1172 refactor: extend misconfiguration API and UI models
  api/openapi.yaml
  api/server/database/gorm/odata.go
  api/server/internal/server/server.gen.go
  api/types/types.gen.go
  cli/families/misconfiguration/fake/scanner.go
  cli/families/misconfiguration/family.go
  cli/families/misconfiguration/family_test.go
  cli/families/misconfiguration/lynis/reportParser.go
  cli/families/misconfiguration/lynis/reportParser_test.go
  cli/families/misconfiguration/types/scannerResult.go
  cli/findingkey/common_test.go
  cli/findingkey/misconfiguration.go
  cli/presenter/apimodel.go
  cli/presenter/apimodel_test.go
  orchestrator/processor/assetscan/misconfigurations.go
  ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.jsx
  ui/src/layout/Findings/Misconfigurations/MisconfigurationTable.jsx
  ui/src/layout/Findings/Misconfigurations/TabMisconfigurationDetails.jsx
  uibackend/openapi.yaml
  uibackend/server/dashboard_findings_impact.go
  uibackend/server/internal/server/server.gen.go
  uibackend/types/types.gen.go
Labels: api

#1185 ci: use Docker Bake for build and push
  .github/workflows/build-and-push-component.yaml
  .github/workflows/reusable-build-and-push.yml
  .github/workflows/reusable-end-to-end-testing.yml
  .github/workflows/reusable-image-names.yml
Labels: ci

#1297 docs: remove documentation already available at openclarity.io
  README.md
  TOUR.md
  assets/vmclarity-arch-20230406.svg
  assets/vmclarity-cf-basic.svg
  assets/vmclarity-dashboard-data.png
  assets/vmclarity-scan-config-summary.png
  assets/vmclarity-scan-list.png
  assets/vmclarity-scan-setup-1.png
  assets/vmclarity-scan-setup-2.png
  assets/vmclarity-scan-setup-3.png
  assets/vmclarity-scan-setup-4.png
  assets/vmclarity-ui-1.png
  assets/vmclarity-ui-2.png
  installation/aws/README.md
  installation/docker/README.md
  installation/gcp/dm/README.md
Labels: documentation

#1320 build: push multiarch images
  Makefile
Labels: build

#1323 ci: improve renovatebot config
  renovate.json
Labels: ci

#1329 ci: pin Alpine image version for testing
  renovate.json
Labels: ci, test:e2e

#1345 fix: yara tools
  Dockerfile.cli
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-UI.json
  installation/azure/vmclarity.json
  installation/azure/vmclarityDeployModule.bicep
  installation/docker/docker-compose.yml
  installation/docker/image_override.env
  installation/gcp/dm/components/vmclarity-server.py.schema
  installation/kubernetes/helm/vmclarity/README.md
  installation/kubernetes/helm/vmclarity/values.yaml
Labels: bug

#1325 build: improve release notes generation
  .github/workflows/release.yaml
  cliff.toml
Labels: documentation, ci

#1354 ci: refactor verification job
  .github/workflows/ci.yml
  .github/workflows/reusable-verification.yml
Labels: ci

#1350 fix: add -C flag to go commands in Makefile
  Makefile
Labels: bug

#1378 fix: Yara Rule Server version in Azure deployment
  installation/azure/vmclarity-UI.json
Labels: bug

#1379 fix: make scanner images consistent across providers
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-UI.json
  installation/azure/vmclarity.bicep
  installation/azure/vmclarity.json
  installation/azure/vmclarityDeployModule.bicep
  installation/docker/image_override.env
  installation/gcp/dm/components/vmclarity-server.py.schema
  installation/gcp/dm/vmclarity.py.schema
Labels: dependencies, docker
