Repository openclarity/vmclarity, pull requests merged in 2024-06, with the labels that each got.

#1716 test: e2e test improvements
  testenv/aws/aws.go
  testenv/aws/utils.go
  testenv/azure/azure.go
  testenv/azure/utils.go
  testenv/gcp/gcp.go
  testenv/utils/ssh.go
Labels: test:e2e

#1764 ci: remove deprecated linters
  .golangci.yml
Labels: ci

#1765 fix(api): use separate model for plugin scanner state
  plugins/openapi.yaml
  plugins/runner/runner.go
  plugins/sdk-go/example/main.go
  plugins/sdk-go/internal/plugin/plugin.gen.go
  plugins/sdk-go/plugin/server.go
  plugins/sdk-go/types/types.gen.go
  plugins/sdk-go/types/types.go
  plugins/sdk-python/example/scanner.py
  plugins/sdk-python/plugin/models/__init__.py
  plugins/sdk-python/plugin/models/state.py
  plugins/sdk-python/plugin/models/status.py
  plugins/sdk-python/plugin/server/server.py
  plugins/store/kics/main.go
Labels: scanners

#1753 feat: report scanner raw output
  .github/workflows/reusable-end-to-end-testing.yml
  .gitignore
  cli/presenter/vmclarity.go
  e2e/go.mod
  e2e/go.sum
  e2e/kics_test.go
  plugins/openapi.yaml
  plugins/sdk-go/internal/plugin/plugin.gen.go
  plugins/sdk-go/types/types.gen.go
  plugins/sdk-python/plugin/models/result.py
  plugins/store/kics/main.go
  scanner/families/plugins/common/results.go
  scanner/families/plugins/family.go
  scanner/families/plugins/result.go
  scanner/families/plugins/runner/runner.go
Labels: enhancement, go, scanner-config

#1767 ci: fix post-release workflow permissions
  .github/workflows/post-release.yaml
Labels: ci

#1768 ci: add new workflow to build container images manually
  .github/workflows/manual-build-and-push.yaml
Labels: ci

#1774 feat: enhance yara scanner
  api/openapi.yaml
  api/server/database/gorm/odata.go
  api/server/internal/server/server.gen.go
  api/types/families.go
  api/types/types.gen.go
  e2e/config/config.go
  orchestrator/watcher/assetscan/families.go
  scanner/families/malware/yara/config/config.go
  scanner/families/malware/yara/yara.go
Labels: enhancement, go

#1796 fix: asset-findings UI fixes
  ui/src/layout/Dashboard/FindingsTabsWidget/index.jsx
  ui/src/layout/Findings/utils.jsx
  ui/src/layout/detail-displays/Findings/index.jsx
Labels: component:ui

#1822 ci(ci): add eslint
  .github/workflows/reusable-verification.yml
  ui/.eslintrc
  ui/package-lock.json
  ui/package.json
  ui/src/components/DoublePaneDisplay/index.test.tsx
  ui/src/components/Form/form-fields/CronField/index.jsx
  ui/vite.config.ts
Labels: javascript, test, ci

#1828 feat(api): add summary to package findings
  api/client/client.go
  api/openapi.yaml
  api/server/database/gorm/finding.go
  api/server/database/gorm/odata.go
  api/server/internal/server/server.gen.go
  api/types/package.go
  api/types/types.gen.go
  e2e/full_scan_test.go
  orchestrator/processor/assetscan/packages.go
  orchestrator/processor/assetscan/processor.go
  orchestrator/processor/assetscan/vulnerabilities.go
  orchestrator/watcher/scan/helpers.go
  orchestrator/watcher/scanconfig/helpers.go
  scanner/utils/utils.go
  scanner/utils/utils_test.go
  ui/src/layout/Findings/FindingsDetailsPage.jsx
  ui/src/layout/Findings/Packages/PackagesTable.jsx
  ui/src/layout/Findings/Packages/TabPackageDetails.jsx
  uibackend/server/dashboard_riskiest_assets_test.go
  uibackend/server/dashboard_riskiest_regions.go
  uibackend/server/dashboard_riskiest_regions_test.go
Labels: enhancement, component:api, component:ui, component:orchestrator
