Repository openclarity/vmclarity, pull requests merged in 2024-08, with the labels that each got.

#1971 fix(scanner): enrich vulnerability data instead of using first vulnerability
  cli/go.mod
  cli/go.sum
  cli/presenter/apimodel.go
  cli/presenter/apimodel_test.go
  core/to/to.go
  e2e/go.mod
  e2e/go.sum
  orchestrator/go.mod
  orchestrator/go.sum
  provider/go.mod
  provider/go.sum
  scanner/families/exploits/family.go
  scanner/families/exploits/family_test.go
  scanner/families/vulnerabilities/types/result.go
  scanner/families/vulnerabilities/types/result_test.go
  scanner/families/vulnerabilities/types/vulnerability.go
  scanner/go.mod
  scanner/go.sum
Labels: bug, scanners

#1977 fix(ui): typos
  ui/src/components/ProgressBar/index.jsx
  ui/src/components/ScanProgressBar/index.jsx
  ui/src/components/SeverityDisplay/index.jsx
  ui/src/components/Table/index.jsx
  ui/src/components/TablePage/index.jsx
  ui/src/components/VulnerabilitiesDisplay/index.jsx
  ui/src/context/FiltersProvider.js
  ui/src/layout/AssetScans/TabAssetScanDetails.jsx
  ui/src/layout/Dashboard/FindingsImpactWidget/index.jsx
  ui/src/layout/Dashboard/FindingsTrendsWidget/index.jsx
  ui/src/layout/Dashboard/RiskiestAssetsWidget/index.jsx
  ui/src/layout/Dashboard/RiskiestRegionsWidget/index.jsx
  ui/src/layout/Dashboard/RiskiestRegionsWidget/riskiest-regions-widget.scss
  ui/src/layout/Findings/FindingsTablePage.jsx
  ui/src/layout/Findings/Vulnerabilities/TabVulnerabilityDetails.jsx
  ui/src/layout/Findings/Vulnerabilities/VulnerabilitiesTable.jsx
  ui/src/layout/Findings/index.jsx
  ui/src/layout/detail-displays/Findings/FindingsSystemFilterLinks/index.jsx
  ui/src/utils/systemConsts.js
  ui/src/utils/utils.jsx
Labels: component:ui

#1974 feat(ci): extend renovate-fix make targets
  Makefile
Labels: repo management, ci

#1986 fix(ui): data display
  ui/src/layout/AssetScans/AssetScansTable.jsx
  ui/src/layout/AssetScans/TabAssetScanDetails.jsx
  ui/src/layout/Assets/AssetsForFindingTable.jsx
  ui/src/layout/Assets/AssetsTable.jsx
  ui/src/layout/Scans/ConfigurationReadOnlyDisplay.jsx
Labels: component:ui

#1987 docs(ci): extend PR template with before/after table
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1985 perf(ui): improve UI queries to reduce load time
  ui/src/layout/AssetScans/AssetScanDetails.jsx
  ui/src/layout/Dashboard/CounterDisplay/index.jsx
  ui/src/layout/Dashboard/index.jsx
  ui/src/layout/Findings/Exploits/ExploitsTable.jsx
  ui/src/layout/Findings/FindingsDetailsPage.jsx
  ui/src/layout/Findings/FindingsTablePage.jsx
  ui/src/layout/Findings/Malware/MalwareTable.jsx
  ui/src/layout/Findings/Misconfigurations/MisconfigurationTable.jsx
  ui/src/layout/Findings/Packages/PackagesTable.jsx
  ui/src/layout/Findings/Rootkits/RootkitsTable.jsx
  ui/src/layout/Findings/Secrets/SecretsTable.jsx
  ui/src/layout/Findings/Vulnerabilities/VulnerabilitiesTable.jsx
  ui/src/layout/Scans/Configurations/ConfigurationDetails/TabConfiguration.jsx
  ui/src/layout/Scans/Scans/ScansTable.jsx
  ui/src/layout/Scans/index.jsx
  ui/src/layout/detail-displays/AssetDetails/AssetScansDisplay.jsx
Labels: component:ui

#1983 chore(ui): use nginx-unprivileged base image for the UI
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-install.sh
  installation/azure/vmclarity.json
  installation/docker/gateway.conf
  installation/gcp/dm/components/vmclarity-install.sh
  installation/kubernetes/helm/vmclarity/README.md
  installation/kubernetes/helm/vmclarity/templates/gateway/configmap.yaml
  installation/kubernetes/helm/vmclarity/templates/ui/deployment.yaml
  installation/kubernetes/helm/vmclarity/values.yaml
  ui/Dockerfile
  ui/nginx.conf
Labels: docker, component:ui

#1990 chore(ui): small cleanup
  ui/src/layout/AssetScans/AssetScanDetails.jsx
  ui/src/layout/Assets/AssetDetails.jsx
  ui/src/layout/Findings/Exploits/ExploitDetails.jsx
  ui/src/layout/Findings/Malware/MalwareDetails.jsx
  ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.jsx
  ui/src/layout/Findings/Packages/PackageDetails.jsx
  ui/src/layout/Findings/Rootkits/RootkitDetails.jsx
  ui/src/layout/Findings/Secrets/SecretDetails.jsx
  ui/src/layout/Findings/Vulnerabilities/VulnerabilityDetails.jsx
  ui/src/layout/Scans/Configurations/ConfigurationActionsDisplay/index.jsx
  ui/src/layout/Scans/Scans/ScanDetails.jsx
  ui/src/utils/utils.jsx
Labels: component:ui
