Repository openclarity/vmclarity, pull requests merged in 2024-01, with the labels that each got.

#1075 chore(deps): use helm version with ORASv2
  .golangci.yml
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: dependencies, go

#1082 chore(deps): use go-viper fork of mapstructure
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: dependencies

#1083 chore(deps): bump OTEL dependencies
  e2e/go.mod
  e2e/go.sum
Labels: dependencies, go

#1084 ci: bump action for artifact upload/download
  .github/workflows/build-and-push-component.yaml
  .github/workflows/release.yaml
Labels: dependencies, github_actions, ci

#1074 refactor(api): asset scan estimation statuses
  api/models/assetscan.go
  api/models/assetscanestimation.go
  api/models/assetscanestimationstatus.go
  api/models/assetscanstatus.go
  api/models/models.gen.go
  api/models/resourcecleanupstatus.go
  api/models/scan.go
  api/models/scanstatus.go
  api/openapi.yaml
  api/server/server.gen.go
  pkg/apiserver/database/gorm/odata.go
  pkg/apiserver/rest/asset_scan_estimation_controller.go
  pkg/orchestrator/assetscanestimationwatcher/watcher.go
  pkg/orchestrator/scanestimationwatcher/watcher.go
  pkg/orchestrator/scanestimationwatcher/watcher_test.go
Labels: go, api

#1089 refactor(api): refactor scan estimation status api object
  api/models/models.gen.go
  api/models/scanestimation.go
  api/models/scanestimationstatus.go
  api/openapi.yaml
  api/server/server.gen.go
  pkg/apiserver/database/gorm/odata.go
  pkg/apiserver/rest/scan_estimation_controller.go
  pkg/orchestrator/scanestimationwatcher/watcher.go
Labels: go, api

#1106 chore: add .envrc to .gitignore, add go.work* to .dockerignore
  .dockerignore
  .gitignore
Labels: ci

#1107 fix(cli): don't return error if home dir doesn't exist
  pkg/shared/families/infofinder/sshtopology/scanner.go
  pkg/shared/families/infofinder/sshtopology/scanner_test.go
Labels: go

#1105 docs: multiple go modules rfc
  rfc/multiple-go-modules.md
Labels: documentation, rfc

#1114 docs: extend misconfiguration scanners rfc
  rfc/extend-misconfiguration-scanners.md
Labels: new scanners, rfc

#1122 docs(aws): update cfn quick-create link to latest release
  README.md
Labels: documentation, aws installer

#1121 ci: group docker dependency updates
  .github/dependabot.yml
Labels: dependencies, ci

#1136 feat(ui): add label to ContainerInfo detail page
  ui/src/layout/detail-displays/AssetDetails/ContainerInfoDetails.jsx
Labels: javascript, ui

#1141 fix(ui): abort scan from the ui
  ui/src/layout/Scans/Scans/ScanActionsDisplay/index.jsx
Labels: javascript, ui
