Repository openclarity/vmclarity, pull requests merged in 2024-07, with the labels that each got.

#1867 feat(plugin): make reportFormats param configurable
  e2e/kics_test.go
  plugins/README.md
  plugins/openapi.yaml
  plugins/sdk-go/internal/plugin/plugin.gen.go
  plugins/sdk-go/types/types.gen.go
  plugins/sdk-python/plugin/models/result.py
  plugins/store/kics/formatter/formatter.go
  plugins/store/kics/main.go
Labels: enhancement, go

#1794 feat(plugin): enable binary plugin support
  .families.yaml
  api/openapi.yaml
  api/server/internal/server/server.gen.go
  api/types/types.gen.go
  cli/state/testdata/effective-config.json
  orchestrator/go.mod
  orchestrator/watcher/assetscan/families.go
  plugins/runner/go.mod
  plugins/runner/go.sum
  plugins/runner/internal/runtimehandler/binary/README.md
  plugins/runner/internal/runtimehandler/binary/handler.go
  plugins/runner/internal/runtimehandler/docker/client.go
  plugins/runner/internal/runtimehandler/docker/handler.go
  plugins/runner/internal/runtimehandler/types.go
  plugins/runner/runner.go
  plugins/runner/runtimehandler.go
  plugins/runner/runtimehandler_linux.go
  plugins/runner/types/types.go
  plugins/sdk-python/example/Dockerfile
  plugins/sdk-python/example/Dockerfile.test
  provider/go.mod
  scanner/families/config.go
  scanner/families/manager.go
  scanner/families/plugins/config.go
  scanner/families/plugins/family.go
  scanner/families/plugins/runner/config/config.go
  scanner/families/plugins/runner/runner.go
  scanner/families/utils/utils.go
  scanner/go.mod
  utils/fsutils/containerrootfs/example/main.go
  utils/fsutils/containerrootfs/todirectory.go
  utils/fsutils/containerrootfs/totempdirectory.go
  utils/go.mod
  utils/go.sum
Labels: scanners

#1848 ci(workflow): enable community contributions
  .github/workflows/build-and-push-component.yaml
  .github/workflows/build-and-push-components-manual.yml
  .github/workflows/build-and-push-components-registry.yml
  .github/workflows/build-and-upload-components.yml
  .github/workflows/cache-cleanup.yml
  .github/workflows/ci.yml
  .github/workflows/image-cleanup.yml
  .github/workflows/main-merge.yml
  .github/workflows/manual-build-and-push.yaml
  .github/workflows/post-release.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build-and-push.yml
  .github/workflows/reusable-end-to-end-testing.yml
  .github/workflows/reusable-verification.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/stale.yml
Labels: github actions, blocked, ci

#1900 feat(ci): add general scope
  .github/workflows/semantic-pr.yml
Labels: ci

#1866 feat(scanner): add cyclonedx gomod from kubeclarity shared analyzer
  .families.yaml
  README.md
  api/types/families.go
  cli/go.mod
  cli/go.sum
  e2e/config/config.go
  e2e/go.mod
  e2e/go.sum
  orchestrator/go.mod
  orchestrator/go.sum
  provider/go.mod
  provider/go.sum
  scanner/families/sbom/cdx_gomod/config/config.go
  scanner/families/sbom/cdx_gomod/cyclonedx_gomod.go
  scanner/families/sbom/cdx_gomod/cyclonedx_gomod_tools.go
  scanner/families/sbom/cdx_gomod/cyclonedx_gomod_tools_test.go
  scanner/families/sbom/factory.go
  scanner/go.mod
  scanner/go.sum
Labels: scanners

#1899 docs(general): update contributing guide and docs
  CONTRIBUTING.md
  docs/assets/scan-config.json
  docs/command_line.md
  docs/configuration.md
  docs/test_e2e.md
  docs/troubleshooting.md
Labels: documentation, ignore-semantic-pr

#1853 feat(ui): add related Assets tab to Finding detail pages
  ui/src/components/Table/index.jsx
  ui/src/layout/AssetScans/AssetScansTable.jsx
  ui/src/layout/Assets/AssetsForFindingTable.jsx
  ui/src/layout/Assets/AssetsTable.jsx
  ui/src/layout/Findings/AssetCountDisplay.jsx
  ui/src/layout/Findings/Exploits/ExploitDetails.jsx
  ui/src/layout/Findings/Exploits/TabExploitDetails.jsx
  ui/src/layout/Findings/Malware/MalwareDetails.jsx
  ui/src/layout/Findings/Malware/TabMalwareDetails.jsx
  ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.jsx
  ui/src/layout/Findings/Misconfigurations/TabMisconfigurationDetails.jsx
  ui/src/layout/Findings/Packages/PackageDetails.jsx
  ui/src/layout/Findings/Packages/TabPackageDetails.jsx
  ui/src/layout/Findings/Rootkits/RootkitDetails.jsx
  ui/src/layout/Findings/Rootkits/TabRootkitDetails.jsx
  ui/src/layout/Findings/Secrets/SecretDetails.jsx
  ui/src/layout/Findings/Secrets/TabSecretDetails.jsx
  ui/src/layout/Findings/Vulnerabilities/TabVulnerabilityDetails.jsx
  ui/src/layout/Findings/Vulnerabilities/VulnerabilityDetails.jsx
  ui/src/layout/Findings/utils.jsx
  ui/src/layout/Scans/Scans/ScansTable.jsx
  ui/src/utils/systemConsts.js
  ui/src/utils/utils.jsx
Labels: component:ui

#1909 chore(ci): change helm install action
  .github/workflows/reusable-end-to-end-testing.yml
Labels: ci

#1927 fix(scanner): add missing append for exploits
  scanner/config.go
Labels: bug, go

#1929 fix(api): return missing finding data
  api/server/database/gorm/odata.go
  orchestrator/processor/assetscan/common.go
Labels: component:api, component:orchestrator

#1931 feat(scanner): extend scanner configs with json tag
  cli/state/testdata/effective-config.json
  scanner/families/exploits/exploitdb/config/config.go
  scanner/families/exploits/types/config.go
  scanner/families/infofinder/types/config.go
  scanner/families/malware/clam/config/config.go
  scanner/families/malware/types/config.go
  scanner/families/malware/yara/config/config.go
  scanner/families/misconfiguration/cisdocker/config/config.go
  scanner/families/misconfiguration/lynis/config/config.go
  scanner/families/misconfiguration/types/config.go
  scanner/families/plugins/runner/config/config.go
  scanner/families/plugins/types/config.go
  scanner/families/rootkits/chkrootkit/config/config.go
  scanner/families/rootkits/types/config.go
  scanner/families/sbom/syft/config/config.go
  scanner/families/sbom/trivy/config/config.go
  scanner/families/sbom/types/config.go
  scanner/families/secrets/gitleaks/config/config.go
  scanner/families/secrets/types/config.go
  scanner/families/vulnerabilities/grype/config/config.go
  scanner/families/vulnerabilities/grype/config/local_grype.go
  scanner/families/vulnerabilities/grype/config/remote_grype.go
  scanner/families/vulnerabilities/trivy/config/config.go
  scanner/families/vulnerabilities/types/config.go
Labels: go, scanners

#1932 refactor(ci): fine-tune Renovatebot
  renovate.json
Labels: ci

#1934 refactor(api): provider status
  api/types/providerstatus.go
  e2e/provider_test.go
Labels: go, provider, test

#1936 fix(ci): use correct Renovatebot manager for Python
  renovate.json
Labels: ci

#1843 feat(api): generate frontend oapi code
  .github/workflows/reusable-verification.yml
  CONTRIBUTING.md
  Makefile
  ui/.eslintrc
  ui/.gitignore
  ui/Dockerfile
  ui/openapitools.json
  ui/package-lock.json
  ui/package.json
  ui/src/api/axiosClient.ts
  ui/src/api/constants.ts
  ui/src/api/vmClarityApi.ts
  ui/src/layout/App/index.jsx
Labels: enhancement, javascript, component:api, component:ui

#1955 fix(e2e): default kics log-level to error to avoid excessive log messages
  core/log/context.go
  e2e/kics_test.go
  e2e/suite_test.go
  plugins/sdk-go/plugin/config.go
  plugins/sdk-go/plugin/logger.go
  plugins/sdk-python/plugin/server/config.py
  plugins/sdk-python/plugin/server/server.py
  plugins/store/kics/main.go
Labels: bug, scanners

#1959 refactor(plugin): add package level mutexes to plugin runtimehandlers
  plugins/runner/internal/runtimehandler/binary/handler.go
  plugins/runner/internal/runtimehandler/docker/handler.go
  scanner/families/plugins/runner/runner.go
Labels: go

#1958 feat(scanner): generate hash concurrently
  scanner/utils/hash.go
  scanner/utils/hash_test.go
  scanner/utils/testdata/test.txt
Labels: go, scanners
